[package]
name = "my_windows_app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.18.0"
winsafe = "0.0.4"
lazy_static = "1.1.1"
[build-dependencies]
windows = "0.18.0"